---
abstract: 'Client library for JA-SIG CAS 2.0 authentication server'
author:
  - 'Olivier Salaun <os AT cru.fr>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AuthCAS
provides:
  AuthCAS:
    file: lib/AuthCAS.pm
    version: 1.6
requires:
  IO::Socket::SSL: 0
  LWP::UserAgent: 0
resources:
  homepage: https://sourcesup.renater.fr/projects/perlcas/
  repository: https://subversion.renater.fr/perlcas/
version: 1.6
